{
 "title": "Fleet Dashboard",
 "tags": [ "summary" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "hmmqtt", "label": "hmmqtt", "query": "influxdb" },
   { "name": "mqtt_measurement", "query": "mqtt_consumer" }
  ]
 },
 "panels": [
  {
   "title": "Cars Connected",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diagnostics",
     "query": "from(bucket: \"something\")\r\n  // range start is fixed , else it will load only selected range devices\r\n  |> range(start: -7d) \r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> map(fn: (r) => ({ r with  _value: 1}))\r\n  |> keep(columns: [\"_time\",\"vin\",\"_value\"]) \r\n  |> aggregateWindow(every: 1d, fn:last, createEmpty: false)\r\n  |> drop(columns: [\"vin\"])\r\n  |> aggregateWindow(every: 1m, fn:count, createEmpty: false)\r\n",
     "select": [
      [
       {
        "params": [
         "diagnostics_odometer_data_value"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Actions Required",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "topic_vin" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "maintenance",
     "query": "timeFrom = -7d\r\ncrash = from(bucket: \"something\")\r\n  |> range(start: timeFrom)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\") \r\n  |> filter(fn: (r) => r[\"capability\"] == \"crash\" and r.property ==\"incidents\")  \r\n  |> aggregateWindow(every: 1s, fn: last, createEmpty: false)\r\n  |> keep(columns: [\"_time\",\"vin\"])\r\n  |> unique(column: \"_time\")\r\n  |> group()\r\n  |> aggregateWindow(every: 1s, fn: count, createEmpty: false, column:\"vin\")\r\n\r\n\r\ntheftAlarm = from(bucket: \"something\")\r\n  |> range(start: timeFrom)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\") \r\n  |> filter(fn: (r) => r[\"capability\"] == \"thief_alarm\" and r.property ==\"status\") \r\n  |> filter(fn: (r) => r._value == \"triggered\") \r\n  |> aggregateWindow(every: 1s, fn: last, createEmpty: false)\r\n  |> keep(columns: [\"_time\",\"vin\"])\r\n  |> unique(column: \"_time\")\r\n  |> group()\r\n  |> aggregateWindow(every: 1s, fn: count, createEmpty: false, column:\"vin\")\r\n\r\n\r\n\r\ndiagnostics = from(bucket: \"something\")\r\n  |> range(start: timeFrom)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\") \r\n  |> filter(fn: (r) => r[\"capability\"] == \"diagnostics\" and r.property ==\"engine_time_to_next_service\") \r\n  |> filter(fn: (r) =>  r._field == \"diagnostics_engine_time_to_next_service_hours\" and r._value <= 0)\r\n  |> aggregateWindow(every: 1s, fn: last, createEmpty: false)\r\n  |> keep(columns: [\"_time\",\"vin\"])\r\n  |> unique(column: \"_time\")\r\n  |> group()\r\n  |> aggregateWindow(every: 1h, fn: count, createEmpty: false, column:\"vin\")\r\n\r\n\r\n\r\nunion(tables: [crash, theftAlarm, diagnostics])\r\n  |> aggregateWindow(every: 1s, fn: last, createEmpty: false, column:\"vin\")\r\n  |> aggregateWindow(every: 1h, fn: sum, createEmpty: true, column:\"vin\")\r\n  |> map(fn: (r) => ({ r with vin: if exists r.vin then r.vin else 0 }))\r\n  |> yield(name: \"end\")",
     "select": [
      [
       {
        "params": [
         "maintenance_next_inspection_date_data"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "capability", "operator": "=", "value": "maintenance" }
     ]
    }
   ]
  },
  {
   "title": "Services Today",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "topic_vin" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "maintenance",
     "query": "startTime = -7d\r\nfrom(bucket: \"something\")\r\n  |> range(start: startTime)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\") \r\n  |> filter(fn: (r) => r[\"capability\"] == \"maintenance\" and r._field == \"time_to_next_service_days\" and r._value <= 1 ) \r\n  |> aggregateWindow(every: 1d, fn: last, createEmpty: false)\r\n  |> keep(columns: [\"_time\",\"vin\"])\r\n  |> group()\r\n  |> aggregateWindow(every: 1s, fn: count, createEmpty: false, column:\"vin\")\r\n  |> aggregateWindow(every: 1h, fn: count, createEmpty: true, column:\"vin\")\r\n  |> yield(name: \"servicesToday\")\r\n",
     "select": [
      [
       {
        "params": [
         "maintenance_next_inspection_date_data"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "capability", "operator": "=", "value": "maintenance" }
     ]
    }
   ]
  },
  {
   "title": "Services This Week",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dashboard_lights",
     "query": "import \"influxdata/influxdb\"\r\nimport \"influxdata/influxdb/v1\"\r\nimport \"experimental\"\r\nimport \"date\"\r\nimport \"dict\"\r\nimport \"generate\"\r\nweekDay = [0: \"Sunday\", 1: \"Monday\", 2: \"Tuesday\", 3: \"Wednesday\", 4: \"Thursday\", 5: \"Friday\", 6: \"Saturday\"]\r\n\r\nweekStartDate = () =>  {\r\n  weekDays = [0: 6, 1: 1, 2: 1, 3: 2, 4: 3, 5: 4, 6: 5]\r\n  daysDuration = dict.get(dict: weekDays, key: date.weekDay(t: today()), default: 0)*24*60*60*1000000000\r\n  timeToReturn = date.truncate(t: experimental.subDuration(d: duration(v: uint(v: daysDuration )), from: now()), unit: 1d)\r\n  return timeToReturn\r\n}\r\n\r\nserviceDate = (eventDate,daysCount) =>  {\r\n  durationTime = duration(v: int(v: daysCount)*24*60*60*1000000000)\r\n  dateToReturn = date.truncate(t: experimental.addDuration(d: durationTime, to: eventDate), unit: 1d)\r\n  return dateToReturn\r\n}\r\n  \r\n\r\ndata = from(bucket: \"something\")\r\n  |> range(start: weekStartDate(), stop: experimental.addDuration(d: 6d23h59m59s, to:  weekStartDate()))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\") \r\n  |> filter(fn: (r) => r[\"capability\"] == \"maintenance\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"time_to_next_service_days\") \r\n  |> aggregateWindow(every: 1d, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with service_date: serviceDate(eventDate: r._time, daysCount: r._value)}))\r\n  |> keep(columns: [\"_time\",\"vin\",\"service_date\"])\r\n  |> filter(fn: (r) => r[\"service_date\"] >= weekStartDate() and  r[\"service_date\"] < experimental.addDuration(d: 7d, to:  weekStartDate())) \r\n  |> map(fn: (r) => ({ r with _time: r.service_date, day_id: date.weekDay(t: r.service_date)}))\r\n  |> group()\r\n  |> aggregateWindow(every: 1ns, fn: count, createEmpty: false, column: \"vin\")\r\n  |> map(fn: (r) => ({ r with tag: string(v: r.vin), _value: date.weekDay(t: r._time) , _time: date.truncate(t: r._time, unit: 1d)}))\r\n  |> drop(columns:[\"_start\",\"_stop\"])\r\n\r\n\r\nt1 = generate.from(count: 7, fn: (n) => n + 1 , start: weekStartDate(), stop: experimental.addDuration(d: 7d, to:  weekStartDate()))\r\n    |> set(key: \"tag\", value: \"0\")\r\n    |> group()\r\n   \r\n\r\nunion(tables: [data, t1])\r\n  |> drop(columns: [\"vin\"])\r\n  |> aggregateWindow(every: 1ns, fn: last, createEmpty: false, column: \"_value\")\r\n  |> map(fn: (r) => ({ r with _value: int(v: r.tag)}))\r\n  |> map(fn: (r) => ({ r with day: dict.get(dict: weekDay, key: date.weekDay(t: r._time ) , default: \"0\")}))\r\n  |> drop(columns:[\"_start\",\"_stop\",\"tag\"])\r\n  |> yield(name: \"end\")\r\n",
     "select": [
      [
       {
        "params": [
         "dashboard_lights_dashboard_lights_data_state"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "tags": [
      { "key": "property", "operator": "=", "value": "dashboard_lights" }
     ]
    }
   ]
  },
  {
   "title": "Actions Required ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "property" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "diagnostics",
       "query": "timeFrom = -10d\r\ncrash = from(bucket: \"something\")\r\n  |> range(start: timeFrom)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\") \r\n  |> filter(fn: (r) => r[\"capability\"] == \"crash\" and r.property ==\"incidents\")  \r\n  |> aggregateWindow(every: 1s, fn: last, createEmpty: false)\r\n  |> keep(columns: [\"_time\",\"vin\"])\r\n  |> unique(column: \"_time\")\r\n  |> map(fn: (r) => ({ r with xevent: \"Crash Detected\" }))\r\n  |> group()\r\n\r\ntheftAlarm = from(bucket: \"something\")\r\n  |> range(start: timeFrom)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\") \r\n  |> filter(fn: (r) => r[\"capability\"] == \"thief_alarm\" and r.property ==\"status\") \r\n  |> filter(fn: (r) => r._value == \"triggered\") \r\n  |> aggregateWindow(every: 1s, fn: last, createEmpty: false)\r\n  |> keep(columns: [\"_time\",\"vin\"])\r\n  |> unique(column: \"_time\")\r\n  |> map(fn: (r) => ({ r with xevent: \"Theft Alarm\" }))\r\n  |> group()\r\n\r\n\r\ndiagnostics = from(bucket: \"something\")\r\n  |> range(start: timeFrom)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\") \r\n  |> filter(fn: (r) => r[\"capability\"] == \"diagnostics\" and r.property ==\"engine_time_to_next_service\") \r\n  |> filter(fn: (r) =>  r._field == \"diagnostics_engine_time_to_next_service_hours\" and r._value <= 0)\r\n  |> aggregateWindow(every: 1s, fn: last, createEmpty: false)\r\n  |> keep(columns: [\"_time\",\"vin\"])\r\n  |> unique(column: \"_time\")\r\n  |> map(fn: (r) => ({ r with xevent: \"Overdue Service\" }))\r\n  |> group()\r\n\r\n\r\nunion(tables: [crash, theftAlarm, diagnostics])\r\n  |> yield(name: \"end\")",
       "select": [
        [
         {
          "params": [
           "diagnostics_odometer_data_value"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Car Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "geomap",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "query": "import \"experimental\"\r\ncoordinates = from(bucket: \"something\")\r\n  |> range(start: today())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\") \r\n  |> filter(fn: (r) => r[\"capability\"] == \"vehicle_location\") \r\n  |> keep(columns: [\"vehicle_location_coordinates_data_latitude\",\"vin\",\"vehicle_location_coordinates_data_longitude\",\"_value\",\"_field\",\"_time\"]) \r\n  |> last()\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"message_id\"])\r\n  |> group()\r\n\r\n\r\nclimate = from(bucket: \"something\")\r\n  |> range(start: today())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\") \r\n  |> filter(fn: (r) => r[\"capability\"] == \"climate\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"climate_outside_temperature_celsius\") \r\n  |> keep(columns: [\"climate_outside_temperature_celsius\",\"vin\",\"_value\",\"_field\",\"_time\"]) \r\n  |> last()\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group()\r\n\r\n\r\nexperimental.join(left: coordinates, right: climate, fn: (left, right) => ({left with climate_outside_temperature_celsius: if exists right.climate_outside_temperature_celsius and right.vin == left.vin  then right.climate_outside_temperature_celsius else float(v: 999999) }))\r\n"
      }
     ]
    }
   ]
  },
  { "title": "Health Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Overall",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"experimental\"\r\nactive = from(bucket: \"something\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\") \r\n  |> filter(fn: (r) =>  r[\"property\"] == \"bulb_failures\" or r[\"property\"] == \"dashboard_lights\" and r._value == \"on\" or  r[\"property\"] == \"trouble_codes\" and r[\"capability\"] == \"diagnostics\" ) \r\n  |> keep(columns: [\"_time\",\"vin\"])\r\n  |> unique(column: \"vin\")  \r\n  |> group()\r\n  |> count(column: \"vin\")\r\n  |> map(fn: (r) => ({ r with active: r.vin}))\r\n  |> drop(columns:[\"vin\"])\r\n  |> yield(name:\"asds\")\r\n\r\ndevices = from(bucket: \"something\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\") \r\n  |> keep(columns: [\"_time\",\"vin\"])\r\n  |> unique(column: \"vin\")\r\n  |> group() \r\n  |> count(column: \"vin\")\r\n  |> map(fn: (r) => ({ r with devices: r.vin}))\r\n  |> drop(columns:[\"vin\"])\r\n  |> yield(name:\"asd\")\r\n\r\n//union(tables: [active, devices])"
    }
   ]
  },
  { "title": "Safe Driving", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Car Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true
  },
  {
   "title": "Car Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true
  }
 ]
}