{
 "title": "Summary",
 "tags": [ "summary" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "hmmqtt", "label": "hmmqtt", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Vehicles currently enrolled",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diagnostics",
     "query": "import \"experimental\"\r\nfrom(bucket: \"something\")\r\n  // range start is fixed , else it will load only selected range devices\r\n  |> range(start: 2010-05-22T23:30:00Z, stop: v.timeRangeStop) \r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dashboard_lights\" or r[\"_measurement\"] == \"diagnostics\")\r\n  |> unique(column: \"topic_vin\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"diagnostics_odometer_data_value\" )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"_table\")\r\n  |> group()\r\n  |> count(column: \"topic_vin\")",
     "select": [
      [
       {
        "params": [
         "diagnostics_odometer_data_value"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Vehicles with overdue service",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "topic_vin" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "maintenance",
     "query": "from(bucket: \"something\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"maintenance\" and r[\"_field\"]==\"maintenance_next_inspection_date_data\")\r\n  |> map(fn: (r) => ({ r with newvalue: (uint(v:uint(v: time(v: r._value )) < uint(v: now()))) }))\r\n  |> filter(fn: (r) => r.newvalue == 1 )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> unique(column: \"topic_vin\")\r\n  |> count(column: \"newvalue\")",
     "select": [
      [
       {
        "params": [
         "maintenance_next_inspection_date_data"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "capability", "operator": "=", "value": "maintenance" }
     ]
    }
   ]
  },
  {
   "title": "Warnings resolved in past week",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "topic_vin" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "maintenance",
     "query": "from(bucket: \"something\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dashboard_lights\") \r\n  |> unique(column: \"topic_vin\")\r\n  |> aggregateWindow(every: 1w, fn: first, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.dashboard_lights_dashboard_lights_data_state == \"on\") \r\n  |> group(columns: [\"_time\"], mode:\"by\")\r\n  |> count(column: \"dashboard_lights_dashboard_lights_data_state\")\r\n  |> group()\r\n  |> yield(name: \"delivered\")",
     "select": [
      [
       {
        "params": [
         "maintenance_next_inspection_date_data"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "capability", "operator": "=", "value": "maintenance" }
     ]
    }
   ]
  },
  {
   "title": "Vehicles with critical health warnings",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dashboard_lights",
     "query": "from(bucket: \"something\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dashboard_lights\") \r\n  |> unique(column: \"topic_vin\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: first, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.dashboard_lights_dashboard_lights_data_state == \"on\") \r\n  |> group(columns: [\"_time\"], mode:\"by\")\r\n  |> count(column: \"dashboard_lights_dashboard_lights_data_state\")\r\n  |> group()\r\n  |> yield(name: \"delivered\")",
     "select": [
      [
       {
        "params": [
         "dashboard_lights_dashboard_lights_data_state"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "tags": [
      { "key": "property", "operator": "=", "value": "dashboard_lights" }
     ]
    }
   ]
  },
  {
   "title": "Daily total distance driven",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "property" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "diagnostics",
     "query": "from(bucket: \"something\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diagnostics\" and r._field == \"diagnostics_odometer_data_value\" ) \r\n  |> group(columns: [\"property\"])\r\n  |> aggregateWindow(every: 1d, fn: last, createEmpty: false)\r\n  |> difference(nonNegative: true, columns: [\"_value\"])\r\n  |> cumulativeSum(columns: [\"_value\"])",
     "select": [
      [
       {
        "params": [
         "diagnostics_odometer_data_value"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Vehicles with Service Due - By Month",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "topic_vin" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "maintenance",
     "query": "from(bucket: \"something\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"maintenance\" and r[\"_field\"]==\"maintenance_next_inspection_date_data\")\r\n  |> map(fn: (r) => ({ r with newvalue: (uint(v:uint(v: time(v: r._value )) < uint(v: now()))) }))\r\n  |> filter(fn: (r) => r.newvalue == 1 )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> unique(column: \"topic_vin\")\r\n",
     "select": [
      [
       {
        "params": [
         "maintenance_next_inspection_date_data"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily total distance driven",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "topic_vin" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "maintenance",
     "query": "from(bucket: \"something\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"maintenance\" and r[\"_field\"]==\"maintenance_next_inspection_date_data\")\r\n  |> map(fn: (r) => ({ r with newvalue: (uint(v:uint(v: time(v: r._value )) < uint(v: now()))) }))\r\n  |> filter(fn: (r) => r.newvalue == 1 )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> unique(column: \"topic_vin\")\r\n",
     "select": [
      [
       {
        "params": [
         "maintenance_next_inspection_date_data"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "capability", "operator": "=", "value": "maintenance" }
     ]
    }
   ]
  }
 ]
}