version: '3.9'
services:
  # MQTT
  mqtt:
    hostname: mqtt
    image: eclipse-mosquitto:2.0.14
    stdin_open: true
    tty: true
    ports:
      - 8883:8883
      - 1883:1883
    volumes:
      - ./data-generator/capabilities:/data-example/
      - ./data-generator/generate.sh:/generate.sh:rw
      - ./mosquitto/conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./tls/:/mosquitto/certs
      - ./mosquitto/data/:/mosquitto/data
  # Grafana
  dashboard:
    env_file: ./influxdb/env.env
    hostname: dashboard
    image: grafana/grafana:8.5.2
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/conf:/usr/share/grafana/conf
    depends_on:
      - influxdb
  # Telegraf
  telegraf:
    env_file: ./influxdb/env.env
    hostname: telegraf
    image: telegraf:1.22.3
    volumes:
      - ./telegraf/:/etc/telegraf
      - ./tls/:/etc/telegraf/mqtt
    depends_on:
      - influxdb
  # InfluxDB
  influxdb:
    env_file: ./influxdb/env.env
    hostname: influxdb
    image: influxdb:2.2.0
    volumes:
      - ./influxdb/data:/var/lib/influxdb
    stdin_open: true
    tty: true
    ports:
      - 8086:8086