apiVersion: 1

deleteDatasources:
  - name: telegraf
    orgId: 1

datasources:
  - name: hmmqtt-flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: ${DOCKER_INFLUXDB_INIT_ORG}
      defaultBucket: ${DOCKER_INFLUXDB_INIT_BUCKET}
      tlsSkipVerify: true
    secureJsonData:
      token: "${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}"
  - name: hmmqtt-influxQL
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    # This database should be mapped to a bucket
    database: ${DOCKER_INFLUXDB_INIT_BUCKET}
    jsonData:
      httpMode: GET
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Token ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}'
